# Copyright 2020-2021, European Organisation for the Exploitation of Meteorological Satellites (EUMETSAT)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

variables: &variables
  BUILD_OPTS: "--output-folder $CI_PROJECT_DIR/conda-channel"
  CHANNEL_OPTS: "-c anaconda -c conda-forge -c file://$CI_PROJECT_DIR/conda-channel"
  CHANNEL_OPTS_WIN: "-c anaconda -c conda-forge -c $env:CI_PROJECT_DIR/conda-channel"
  EPCT_TEST_DATA_DIR: "/data/data-tailor"


stages:
  - docs
  - build
  - test
  - performance
  - deploy


pdf docs:
  stage: docs
  tags:
    - linux
  image: sphinxdoc/sphinx-latexpdf
  when: manual
  script:
    - mkdir -p pdf-docs
    - cd documentation
    - |
      for f in */; do cd $f;
      if [ -f Makefile ]; then
        make latexpdf LATEXOPTS="-interaction=nonstopmode" && make latexpdf LATEXOPTS="-interaction=nonstopmode" && cp _build/latex/*.pdf ../../pdf-docs/; cd -;
      else
        cd -;
      fi;done
  artifacts:
    paths:
      - pdf-docs
    expire_in: 7 days

build linux:
  stage: build
  tags:
    - linux
  image: conda/miniconda3-centos7:latest
  before_script:
    - conda update -n base -c defaults conda
    - conda install -y conda-build
    - cd conda
  script:
    - conda build $BUILD_OPTS .
  artifacts:
    paths:
      - $CI_PROJECT_DIR/conda-channel
    expire_in: 10 days

build win32:
  stage: build
  tags:
    - windows
  before_script:
    - invoke-expression -Command C:\BuildTools\Microsoft.PowerShell_profile.ps1
  script:
    - conda install -y conda-build
    - mkdir $env:CI_PROJECT_DIR\conda-channel
    - cd conda
    - 'cmd.exe /k "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars32.bat" "&" set CONDA_FORCE_32BIT=1 "&" conda build --output-folder $env:CI_PROJECT_DIR\conda-channel .' 
  artifacts:
    paths:
      - $env:CI_PROJECT_DIR\conda-channel
    expire_in: 10 days

build win64:
  stage: build
  tags:
    - windows
  before_script:
    - invoke-expression -Command C:\BuildTools\Microsoft.PowerShell_profile.ps1
  script:
    - conda install -y conda-build
    - mkdir $env:CI_PROJECT_DIR\conda-channel
    - cd conda
    - 'cmd.exe /k "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat" "&" conda build --output-folder $env:CI_PROJECT_DIR\conda-channel .'
  artifacts:
    paths:
      - $env:CI_PROJECT_DIR\conda-channel
    expire_in: 10 days


test linux py39:
  stage: test
  tags:
    - linux
  image: conda/miniconda3-centos7:latest
  dependencies:
    - build linux
  needs:
    - build linux
  before_script:
    - conda init bash
    - source ~/.bashrc
    - conda create -y --name $CI_JOB_ID python=3.9
    - conda activate $CI_JOB_ID
    - conda update -n base -c defaults conda
  script:
    - conda install -y $CHANNEL_OPTS fcidecomp pytest
    - pytest -vv tests
    - conda deactivate

test win32 py39:
  stage: test
  tags:
    - windows
  dependencies:
    - build win32
  needs:
    - build win32
  before_script:
    - $env:CONDA_FORCE_32BIT=1
    - invoke-expression -Command C:\BuildTools\Microsoft.PowerShell_profile.ps1
    - conda create -y --name $env:CI_JOB_ID python=3.9
    - conda activate $env:CI_JOB_ID
  script:
    - conda install -y -c anaconda -c conda-forge -c $env:CI_PROJECT_DIR/conda-channel fcidecomp pytest
    - conda deactivate
    - conda activate $env:CI_JOB_ID
    - $env:EPCT_TEST_DATA_DIR="C:\\BuildTools\test-data"
    - pytest -vv tests
    - conda deactivate
    - conda env remove -n $env:CI_JOB_ID

test win64 py39:
  stage: test
  tags:
    - windows
  dependencies:
    - build win64
  needs:
    - build win64
  before_script:
    - invoke-expression -Command C:\BuildTools\Microsoft.PowerShell_profile.ps1
    - conda create -y --name $env:CI_JOB_ID python=3.9
    - conda activate $env:CI_JOB_ID
  script:
    - conda install -y -c anaconda -c conda-forge -c $env:CI_PROJECT_DIR/conda-channel fcidecomp pytest
    - conda deactivate
    - conda activate $env:CI_JOB_ID
    - $env:EPCT_TEST_DATA_DIR="C:\\BuildTools\test-data"
    - pytest -vv tests
    - conda deactivate
    - conda env remove -n $env:CI_JOB_ID


test linux py38:
  stage: test
  tags:
    - linux
  image: conda/miniconda3-centos7:latest
  when: manual
  dependencies:
    - build linux
  needs:
    - build linux
  before_script:
    - conda init bash
    - source ~/.bashrc
    - conda create -y --name $CI_JOB_ID python=3.8
    - conda activate $CI_JOB_ID
    - conda update -n base -c defaults conda
  script:
    - conda install -y $CHANNEL_OPTS fcidecomp pytest
    - pytest -vv tests
    - conda deactivate

test win32 py38:
  stage: test
  tags:
    - windows
  when: manual
  dependencies:
    - build win32
  needs:
    - build win32
  before_script:
    - $env:CONDA_FORCE_32BIT=1
    - invoke-expression -Command C:\BuildTools\Microsoft.PowerShell_profile.ps1
    - conda create -y --name $env:CI_JOB_ID python=3.8
    - conda activate $env:CI_JOB_ID
  script:
    - conda install -y -c anaconda -c conda-forge -c $env:CI_PROJECT_DIR/conda-channel fcidecomp pytest
    - conda deactivate
    - conda activate $env:CI_JOB_ID
    - $env:EPCT_TEST_DATA_DIR="C:\\BuildTools\test-data"
    - pytest -vv tests
    - conda deactivate
    - conda env remove -n $env:CI_JOB_ID

test win64 py38:
  stage: test
  tags:
    - windows
  when: manual
  dependencies:
    - build win64
  needs:
    - build win64
  before_script:
    - invoke-expression -Command C:\BuildTools\Microsoft.PowerShell_profile.ps1
    - conda create -y --name $env:CI_JOB_ID python=3.8
    - conda activate $env:CI_JOB_ID
  script:
    - conda install -y -c anaconda -c conda-forge -c $env:CI_PROJECT_DIR/conda-channel fcidecomp pytest
    - conda deactivate
    - conda activate $env:CI_JOB_ID
    - $env:EPCT_TEST_DATA_DIR="C:\\BuildTools\test-data"
    - pytest -vv tests
    - conda deactivate
    - conda env remove -n $env:CI_JOB_ID


test linux py37:
  stage: test
  tags:
    - linux
  image: conda/miniconda3-centos7:latest
  when: manual
  dependencies:
    - build linux
  needs:
    - build linux
  before_script:
    - conda init bash
    - source ~/.bashrc
    - conda create -y --name $CI_JOB_ID python=3.7
    - conda activate $CI_JOB_ID
    - conda update -n base -c defaults conda
  script:
    - conda install -y $CHANNEL_OPTS fcidecomp pytest
    - pytest -vv tests
    - conda deactivate

test win32 py37:
  stage: test
  tags:
    - windows
  when: manual
  dependencies:
    - build win32
  needs:
    - build win32
  before_script:
    - $env:CONDA_FORCE_32BIT=1
    - invoke-expression -Command C:\BuildTools\Microsoft.PowerShell_profile.ps1
    - conda create -y --name $env:CI_JOB_ID python=3.7
    - conda activate $env:CI_JOB_ID
  script:
    - conda install -y -c anaconda -c conda-forge -c $env:CI_PROJECT_DIR/conda-channel fcidecomp pytest
    - conda deactivate
    - conda activate $env:CI_JOB_ID
    - $env:EPCT_TEST_DATA_DIR="C:\\BuildTools\test-data"
    - pytest -vv tests
    - conda deactivate
    - conda env remove -n $env:CI_JOB_ID

test win64 py37:
  stage: test
  tags:
    - windows
  when: manual
  dependencies:
    - build win64
  needs:
    - build win64
  before_script:
    - invoke-expression -Command C:\BuildTools\Microsoft.PowerShell_profile.ps1
    - conda create -y --name $env:CI_JOB_ID python=3.7
    - conda activate $env:CI_JOB_ID
  script:
    - conda install -y -c anaconda -c conda-forge -c $env:CI_PROJECT_DIR/conda-channel fcidecomp pytest
    - conda deactivate
    - conda activate $env:CI_JOB_ID
    - $env:EPCT_TEST_DATA_DIR="C:\\BuildTools\test-data"
    - pytest -vv tests
    - conda deactivate
    - conda env remove -n $env:CI_JOB_ID


performance linux py39:
  stage: performance
  tags:
    - linux
  when: manual
  image: conda/miniconda3-centos7:latest
  dependencies:
    - build linux
  needs:
    - build linux
    - test linux py39
  before_script:
    - conda init bash
    - source ~/.bashrc
    - conda create -y --name $CI_JOB_ID python=3.9
    - conda activate $CI_JOB_ID
    - conda update -n base -c defaults conda
  script:
    - conda install -y $CHANNEL_OPTS fcidecomp pytest pytest-benchmark
    - pytest -vv perf
    - conda deactivate

performance win32 py39:
  stage: performance
  tags:
    - windows
  when: manual
  dependencies:
    - build win32
  needs:
    - build win32
    - test win32 py39
  before_script:
    - $env:CONDA_FORCE_32BIT=1
    - if (Test-Path -Path C:\Users\Admin\) {invoke-expression -Command C:\Users\Admin\Documents\WindowsPowerShell\profile.ps1}
    - conda create -y --name $env:CI_JOB_ID python=3.9
    - conda activate $env:CI_JOB_ID
  script:
    - conda install -y -c anaconda -c conda-forge -c $env:CI_PROJECT_DIR/conda-channel fcidecomp pytest pytest-benchmark
    - conda deactivate
    - conda activate $env:CI_JOB_ID
    - $env:EPCT_TEST_DATA_DIR="C:\\BuildTools\test-data"
    - pytest -vv perf
    - conda deactivate
    - conda env remove -n $env:CI_JOB_ID

performance win64 py39:
  stage: performance
  tags:
    - windows
  when: manual
  dependencies:
    - build win64
  needs:
    - build win64
    - test win64 py39
  before_script:
    - if (Test-Path -Path C:\Users\Admin\) {invoke-expression -Command C:\Users\Admin\Documents\WindowsPowerShell\profile.ps1}
    - conda create -y --name $env:CI_JOB_ID python=3.9
    - conda activate $env:CI_JOB_ID
  script:
    - conda install -y -c anaconda -c conda-forge -c $env:CI_PROJECT_DIR/conda-channel fcidecomp pytest pytest-benchmark
    - conda deactivate
    - conda activate $env:CI_JOB_ID
    - $env:EPCT_TEST_DATA_DIR="C:\\BuildTools\test-data"
    - pytest -vv perf
    - conda deactivate
    - conda env remove -n $env:CI_JOB_ID


deploy local:
  stage: deploy
  tags:
    - linux
  image: conda/miniconda3-centos7:latest
  dependencies:
    - build linux
    - build win32
    - build win64
  needs:
    - build linux
    - build win32
    - build win64
    - test linux py39
    - test win64 py39
    - test win32 py39
  before_script:
    - conda install -y conda-build
  script:
    - conda index $CI_PROJECT_DIR/conda-channel
  artifacts:
    paths:
      - $CI_PROJECT_DIR/conda-channel
    expire_in: 10 days
