# Copyright 2020-2021, European Organisation for the Exploitation of Meteorological Satellites (EUMETSAT)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

variables: &variables
  BUILD_OPTS: "--output-folder conda-channel"
  CONDABIN: 'C:\ProgramData\Miniconda3\Library\bin;C:\ProgramData\Miniconda3\Scripts;C:\Users\datatailor_admin\miniconda3\condabin;C:\Users\datatailor_admin\miniconda3\Scripts;C:\Users\datatailor_admin\miniconda3\Library\bin'
  CHANNEL_OPTS: "--override-channels -c anaconda -c conda-forge -c file://$CI_PROJECT_DIR/conda/conda-channel"
  CHANNEL_OPTS_WIN: "--override-channels -c defaults -c conda-forge -c file://$env:CI_PROJECT_DIR/conda-channel"
  GIT_STRATEGY: "fetch"
  GIT_FETCH_EXTRA_FLAGS: --prune --refmap=

stages:
  - docs
  - build
  - test

pdf docs:
  image: sphinxdoc/sphinx-latexpdf
  stage: docs
  script:
    - mkdir -p pdf-docs
    - cd documentation
    - |
      for f in */; do cd $f;
      if [ -f Makefile ]; then
        make latexpdf LATEXOPTS="-interaction=nonstopmode" && make latexpdf LATEXOPTS="-interaction=nonstopmode" && cp _build/latex/*.pdf ../../pdf-docs/; cd -;
      else
        cd -;
      fi;done
  tags:
    - linux
  when: manual
  artifacts:
    paths:
      - pdf-docs
    expire_in: 7 days

build conda centos7:
  image: conda/miniconda3-centos7:latest
  tags:
    - linux
  stage: build
  before_script:
    - conda update -n base -c defaults conda
    - conda install -y conda-build
    - mkdir -p /usr/local/conda-bld
    - conda index /usr/local/conda-bld
    - conda clean --all --yes
    - cd conda
  script:
    - conda build $BUILD_OPTS .
    - conda build purge
  artifacts:
    paths:
      - conda/conda-channel
    expire_in: 10 days

build conda windows 32bit:
  tags:
    - windows
  stage: build
  script:
    - $env:Path = "$env:CONDABIN;$env:Path"
    - conda install -y conda-build
    - mkdir $env:CI_PROJECT_DIR\conda-channel
    - cd conda
    - 'cmd.exe /k "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars32.bat" "&" set CONDA_FORCE_32BIT=1 "&" conda create -y --name fcidecomp32 python=3.9"&" conda activate fcidecomp32 "&" conda build --output-folder $env:CI_PROJECT_DIR\conda-channel . "&" conda build purge' 
  artifacts:
    paths:
      - $env:CI_PROJECT_DIR\conda-channel
    expire_in: 10 days

build conda windows 64bit:
  tags:
    - windows
  stage: build
  script:
    - $env:Path = "$env:CONDABIN;$env:Path"
    - conda install -y conda-build
    - mkdir $env:CI_PROJECT_DIR\conda-channel
    - cd conda
    - 'cmd.exe /k "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat" "&" conda build --output-folder $env:CI_PROJECT_DIR\conda-channel .'
  artifacts:
    paths:
      - $env:CI_PROJECT_DIR\conda-channel
    expire_in: 10 days

test conda centos7:
  image: conda/miniconda3-centos7:latest
  dependencies:
    - build conda centos7
  tags:
    - linux
  stage: test
  before_script:
    - conda init bash
    - source ~/.bashrc
    - conda activate
    - conda update -n base -c defaults conda
    - conda install -y netcdf4 xarray pytest
  script:
    - conda install -y $CHANNEL_OPTS fcidecomp
    - pytest
  artifacts:
    paths:
      - tests/test-data
    expire_in: 10 days

test conda windows 32bit:
  dependencies:
    - build conda windows 32bit
  tags:
    - windows
  stage: test
  before_script:
    - $env:CONDA_FORCE_32BIT=1
    - if (Test-Path -Path C:\Users\Admin\) {invoke-expression -Command C:\Users\Admin\Documents\WindowsPowerShell\profile.ps1}
    - conda create -y --name $env:CI_JOB_ID python=3.9
  script:
    - conda activate $env:CI_JOB_ID
    - conda env list
    - conda install -y netcdf4 xarray pytest
    - conda install -y --override-channels -c defaults -c conda-forge -c $env:CI_PROJECT_DIR\conda-channel fcidecomp
    - echo %HDF5_PLUGIN_PATH%
    - pytest -vv
    - conda deactivate
    - conda env remove -n $env:CI_JOB_ID
  artifacts:
    paths:
      - tests/test-data
    expire_in: 10 days

test conda windows 64bit:
  dependencies:
    - build conda windows 64bit
  tags:
    - windows
  stage: test
  before_script:
    - if (Test-Path -Path C:\Users\Admin\) {invoke-expression -Command C:\Users\Admin\Documents\WindowsPowerShell\profile.ps1}
    - conda create -y --name $env:CI_JOB_ID python=3.9
    - conda activate $env:CI_JOB_ID
    - conda env list
    - conda install -y netcdf4 xarray pytest
  script:
    - conda install -y --override-channels -c defaults -c conda-forge -c $env:CI_PROJECT_DIR\conda-channel fcidecomp
    - echo %HDF5_PLUGIN_PATH%
    - pytest -vv
    - conda deactivate
    - conda env remove -n $env:CI_JOB_ID
  artifacts:
    paths:
      - tests/test-data
    expire_in: 10 days
