# Code inspired by:
# - https://github.com/conda-forge/charls-feedstock/blob/master/recipe/build.sh
# - https://github.com/mraspaud/fcidecomp-conda-recipe/blob/master/build.sh

{% set version = "1.0.2" %}
{% set charls_version = "2.1.0" %}

package:
  name: fcidecomp
  version: {{ version }}

source:
  - url: https://github.com/team-charls/charls/archive/{{ charls_version }}.tar.gz # [win32]
  - path: ../src/

build:
  number: 7

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - m2-patch                      # [win]
    - make                          # [not win]
    - ninja                         # [win]
  host:
    - charls=2.1.0                  # [not win32]
    - hdf5=1.10.*
    - h5py=2.*                      # [not win]
    - h5py=3.6.0                    # [win]
    - python  {{ python }}
    - zlib
  run:
    - charls=2.1.0                  # [not win32]
    - hdf5=1.10.*
    - h5py=2.*                      # [not win]
    - h5py=3.6.0                    # [win]
    - libnetcdf!=4.8.0              # [win]
    - libssh2                       # [win]
    - netcdf4
    - python  {{ python }}
