# Code inspired by:
# - https://github.com/conda-forge/charls-feedstock/blob/master/recipe/build.sh
# - https://github.com/mraspaud/fcidecomp-conda-recipe/blob/master/build.sh

{% set setup_data = load_setup_py_data(setup_file='../src/fcidecomp-python/setup.py', from_recipe_dir=True) %}
{% set charls_version = "2.4.2" %}

package:
  name: fcidecomp
  version: "{{ setup_data.get('version').replace('-', '_').strip() }}"

source:
  - url: https://github.com/team-charls/charls/archive/{{ charls_version }}.tar.gz # [win32]
  - path: ../src/

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - m2-patch              # [win]
    - make                  # [not win]
    - ninja                 # [win]
  host:
    - charls>=2.1.0          # [not win32]
    - h5py>=3.6.0            # [win]
    - python  {{ python }}
    - zlib
  run:
    - charls>=2.1.0          # [not win32]
    - h5py>=3.6.0            # [win]
    - libnetcdf!=4.8.0      # [win]
    - libssh2               # [win]
    - netcdf4
    - python  {{ python }}
