# Code inspired by:
# - https://github.com/conda-forge/charls-feedstock/blob/master/recipe/build.sh
# - https://github.com/mraspaud/fcidecomp-conda-recipe/blob/master/build.sh

{% set version = "1.0.2" %}

package:
  name: fcidecomp
  version: {{ version }}

source:
  - path: ../src/

build:
  number: 6

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make   # [not win]
    - ninja  # [win]
  host:
    - python  {{ python }}
    - zlib
    - charls=2.1.0
    - hdf5=1.10.*
    - h5py=2.*
  run:
    - python  {{ python }}
    - charls=2.1.0
    - hdf5=1.10.*
    - h5py=2.*