{% set version = "1.0.2" %}

package:
  name: fcidecomp
  version: {{ version }}

source:
  - git_url: https://github.com/team-charls/charls.git
    git_tag: 1.x-master
    folder: charls
  - path: ../fcidecomp-src/EUMETSAT-FCIDECOMP_V{{ version }}

build:
  number: 5

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
  host:
    - zlib
    - hdf5>=1.10.5
  run:
    - hdf5>=1.10.5