# Code inspired by:
# - https://github.com/conda-forge/charls-feedstock/blob/master/recipe/build.sh
# - https://github.com/mraspaud/fcidecomp-conda-recipe/blob/master/build.sh

{% set version = "1.0.2" %}

package:
  name: fcidecomp
  version: {{ version }}

source:
  - path: ../src/

build:
  number: 6

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make   # [not win]
    - ninja  # [win]
  host:
    - python  {{ python }}
    - zlib
    - charls=2.1.0
    - hdf5=1.10.*
    - h5py=2.*
  run:
    - python  {{ python }}
    - charls=2.1.0
    - hdf5=1.10.*
    - h5py=2.*

test:
  commands:
    - test -f $PREFIX/lib/libCharLS${SHLIB_EXT}     # [unix]
    - test -f $PREFIX/include/CharLS/header.h       # [unix]
    - if not exist %LIBRARY_LIB%\\charls-2-x64.lib exit 1       # [win]
    - if not exist %LIBRARY_BIN%\\charls-2-x64.dll exit 1       # [win]
    - if not exist %LIBRARY_INC%\\charls\\charls.h exit 1       # [win]